[package]
name = "local-computer-use"
version = "0.1.0"
description = "A Tauri App"
authors = ["Luke Sutor"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_nextjs_template_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
tokio = { version = "1.42.0", features = ["macros"] }
screenshots = "0.8.10"
image = "0.25.5"
tauri-plugin-fs = "2"
once_cell = "1.21.3"
rusqlite = { version = "*", features = ["bundled"] }
sqlite-vec = "0.1.6"
rusqlite_migration = "1.3.1"
lazy_static = "1.5.0"
zerocopy = "0.8.25"
fastembed = "4.8.0"
reqwest = "0.12.15"
tokio-stream = { version = "0.1.17", features = ["net"] }
chrono = "0.4.41"
axum = { version = "0.6", features = ["ws"] }
futures = "0.3.4"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
